# PROXY MANAGER
# Docs: https://nginxproxymanager.com
# Panel: http://YOUR-SERVER-IP:81

# Go ahead and hit DEPLOY!


# Joins to the `marina` network
networks:
    default:
        name: marina
        external: true

# Automatically creates `external` volumes at /var/lib/docker/volumes
volumes:
    proxy:
        external: true
    letsencrypt:
        external: true

# The Proxy Manager
services:
    proxy:
        image: jc21/nginx-proxy-manager:latest
        ports:
            - 80:80
            - 81:81
            - 443:443
        volumes:
            - proxy:/data
            - letsencrypt:/etc/letsencrypt

