# DO NOT MAP SERVICE PORTS HERE!
#
# Expose the `services` through the Proxy Manager admin panel:
#  - For the `domain`: something like `my-app1.com`.
#  - For the `host`: use the `service` names like `app1`.
#  - For the `port`: you need to know what port each container exposes.


# The same network as the Proxy Manager
networks:
    default:
        name: marina
        external: true


# Zero downtime deployment works because of `healthcheck` and `deploy` settings
services:
    app1:
        image: my-private-registry/app1:production
        env_file: .env.app1
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:<port>" ]
            start_period: 120s
            interval: 5s
            timeout: 10s
            retries: 3
        deploy:
            update_config:
                order: start-first
                failure_action: rollback

    app2:
        image: my-private-registry/app2:production
        env_file: .env.app2
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:<port>" ]
            start_period: 120s
            interval: 5s
            timeout: 10s
            retries: 3
        deploy:
            update_config:
                order: start-first
                failure_action: rollback


