#### NETWORKS ####
networks:
    default:
        name: marina
        external: true

#### VOLUMES ####
volumes:
    mary-db:
        external: true
    flow-db:
        external: true
    paper-db:
        external: true
    orange-db:
        external: true
    ping-db:
        external: true

services:
    ######## ORANGE ########
    mary:
        image: ghcr.io/robsontenorio/mary-ui.com:production
        env_file: .env.mary
        volumes:
            - mary-db:/var/www/app/database/
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
            start_period: 120s
            interval: 5s
            timeout: 10s
            retries: 3
        deploy:
            update_config:
                order: start-first
                failure_action: rollback

    ######## ORANGE ########
    orange:
        image: ghcr.io/robsontenorio/orange.mary-ui.com:production
        env_file: .env.orange
        volumes:
            - orange-db:/var/www/app/database/
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
            start_period: 120s
            interval: 5s
            timeout: 10s
            retries: 3
        deploy:
            update_config:
                order: start-first
                failure_action: rollback

    ######## PAPER ########
    paper:
        image: ghcr.io/robsontenorio/paper.mary-ui.com:production
        env_file: .env.paper
        volumes:
            - paper-db:/var/www/app/database/
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
            start_period: 120s
            interval: 5s
            timeout: 10s
            retries: 3
        deploy:
            update_config:
                order: start-first
                failure_action: rollback

    ######## FLOW ########
    flow:
        image: ghcr.io/robsontenorio/flow.mary-ui.com:production
        env_file: .env.flow
        volumes:
            - flow-db:/var/www/app/database/
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
            start_period: 120s
            interval: 5s
            timeout: 10s
            retries: 3
        deploy:
            update_config:
                order: start-first
                failure_action: rollback

    ######## PING ########
    ping:
        image: ghcr.io/robsontenorio/ping.mary-ui.com:production
        env_file: .env.ping
        volumes:
            - ping-db:/var/www/app/database/
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:8080/up" ]
            start_period: 120s
            interval: 5s
            timeout: 10s
            retries: 3
        deploy:
            update_config:
                order: start-first
                failure_action: rollback
