#### NETWORKS ####
networks:
    default:
        name: marina
        external: true

#### VOLUMES ####
volumes:
    flow-db:
        external: true
    paper-db:
        external: true
    orange-db:
        external: true
    ping-db:
        external: true

services:
    ######## ORANGE ########
    orange:
        image: ghcr.io/robsontenorio/orange.mary-ui.com:production
        env_file: .env.orange
        volumes:
            - orange-db:/var/www/app/database/
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:8000/up" ]
            start_period: 120s
            interval: 5s
            timeout: 10s
            retries: 3
        deploy:
            update_config:
                order: start-first
                failure_action: rollback
            labels:
                - "traefik.http.routers.orange.rule=Host(`orange.maryui.com`)"
                - "traefik.http.services.orange.loadbalancer.server.port=8000"

    ######## PAPER ########
    paper:
        image: ghcr.io/robsontenorio/paper.mary-ui.com:production
        env_file: .env.paper
        volumes:
            - paper-db:/var/www/app/database/
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:8000/up" ]
            start_period: 120s
            interval: 5s
            timeout: 10s
            retries: 3
        deploy:
            update_config:
                order: start-first
                failure_action: rollback
            labels:
                - "traefik.http.routers.paper.rule=Host(`paper.maryui.com`)"
                - "traefik.http.services.paper.loadbalancer.server.port=8000"

    ######## FLOW ########
    flow:
        image: ghcr.io/robsontenorio/flow.mary-ui.com:production
        env_file: .env.flow
        volumes:
            - flow-db:/var/www/app/database/
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:8000/up" ]
            start_period: 120s
            interval: 5s
            timeout: 10s
            retries: 3
        deploy:
            update_config:
                order: start-first
                failure_action: rollback
            labels:
                # 🌐 HTTP
                - "traefik.http.routers.flow.rule=Host(`flow.maryui.com`)"
                - "traefik.http.services.flow.loadbalancer.server.port=8000"

                # 🔁 Forces https for Livewire file uploads
                - "traefik.http.middlewares.flow-https.headers.customrequestheaders.X-Forwarded-Proto=https"
                - "traefik.http.middlewares.flow-https.headers.customrequestheaders.X-Forwarded-Port=443"
                - "traefik.http.routers.flow.middlewares=flow-https"

    ######## PING ########
    ping:
        image: ghcr.io/robsontenorio/ping.mary-ui.com:production
        env_file: .env.ping
        volumes:
            - ping-db:/var/www/app/database/
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:8000/up" ]
            start_period: 120s
            interval: 5s
            timeout: 10s
            retries: 3
        deploy:
            update_config:
                order: start-first
                failure_action: rollback
            labels:
                # 🔁 WebSocket → port 8099
                - "traefik.http.routers.ping-ws.rule=Host(`ping.maryui.com`) && PathPrefix(`/app`)"
                - "traefik.http.routers.ping-ws.service=ping-ws"
                - "traefik.http.services.ping-ws.loadbalancer.server.port=8099"

                # 🌐 HTTP  → port 8000
                - "traefik.http.routers.ping-http.rule=Host(`ping.maryui.com`)"
                - "traefik.http.routers.ping-http.service=ping-http"
                - "traefik.http.services.ping-http.loadbalancer.server.port=8000"
