services:
    ######## APP ########
    marina:
        build:
            context: ..
            dockerfile: .docker/Dockerfile
            target: base
        group_add:
            - root
        environment:
            - SERVER_NAME=:8787
        volumes:
            - ../:/app:cached
            - /var/run/docker.sock:/var/run/docker.sock:ro
        ports:
            - 8787:8787
            - 5717:5717


