services:
    ######## APP ########
    marina-app:
        build:
            context: ..
            dockerfile: .docker/Dockerfile
            target: local
        environment:
            - CONTAINER_ROLE=APP
        volumes:
            - ../:/var/www/app
            - /var/run/docker.sock:/var/run/docker.sock
            - ~/.docker/config.json:/root/.docker/config.json
            - marina_data:/var/www/app/.data
        ports:
            - "8787:8080"
            - "5717:5717"
volumes:
    marina_data:


