services:
    ######## APP ########
    marina:
        build:
            context: ..
            dockerfile: .docker/Dockerfile
            target: local
        group_add:
            - root
        volumes:
            - ../:/var/www/app
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - 8787:8080
            - 5717:5717


