services:

    ####### PROXY ##########
    mary-proxy:
        #image: jc21/nginx-proxy-manager:latest
        image: jc21/nginx-proxy-manager:github-pr-3478
        ports:
            - 80:80
            - 81:81
            - 443:443
        volumes:
            - mary-proxy-data:/data
            - mary-proxy-letsencrypt:/etc/letsencrypt

    ######## SHEPHERD  ########
    mary-shepherd:
        image: containrrr/shepherd:latest
        environment:
            SLEEP_TIME: '30s'
            FILTER_SERVICES: 'label=shepherd.autodeploy=true'
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - /root/.docker/config.json:/root/.docker/config.json:ro

    ######## MARY ########
    mary-app:
        image: ghcr.io/robsontenorio/mary-ui.com:production
        env_file: .env.mary
        volumes:
            - mary-db:/var/www/app/database/
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
            start_period: 120s
            interval: 5s
            timeout: 10s
            retries: 3
        deploy:
            labels:
                - shepherd.autodeploy=true
            update_config:
                order: start-first
                failure_action: rollback

    ######## PAPER ########
    paper-app:
        image: ghcr.io/robsontenorio/paper.mary-ui.com:production
        env_file: .env.paper
        volumes:
            - paper-db:/var/www/app/database/
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
            start_period: 120s
            interval: 5s
            timeout: 10s
            retries: 3
        deploy:
            labels:
                - shepherd.autodeploy=true
            update_config:
                order: start-first
                failure_action: rollback

    ######## ORANGE ########
    orange-app:
        image: ghcr.io/robsontenorio/orange.mary-ui.com:production
        env_file: .env.orange
        volumes:
            - orange-db:/var/www/app/database/
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
            start_period: 120s
            interval: 5s
            timeout: 10s
            retries: 3
        deploy:
            labels:
                - shepherd.autodeploy=true
            update_config:
                order: start-first
                failure_action: rollback

    ######## FLOW ########
    flow-app:
        image: ghcr.io/robsontenorio/flow.mary-ui.com:production
        env_file: .env.flow
        volumes:
            - flow-db:/var/www/app/database/
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
            start_period: 120s
            interval: 5s
            timeout: 10s
            retries: 3
        deploy:
            labels:
                - shepherd.autodeploy=true
            update_config:
                order: start-first
                failure_action: rollback

    ######## PING ########
    ping-app:
        image: ghcr.io/robsontenorio/ping.mary-ui.com:production
        env_file: .env.ping
        volumes:
            - ping-db:/var/www/app/database/
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:8080/up" ]
            start_period: 120s
            interval: 5s
            timeout: 10s
            retries: 3
        deploy:
            labels:
                - shepherd.autodeploy=true
            update_config:
                order: start-first
                failure_action: rollback

#### NETWORKS ####
networks:
    default:
        name: mary
        external: true

#### VOLUMES ####
volumes:
    mary-proxy-data:
        external: true
    mary-proxy-letsencrypt:
        external: true
    mary-db:
        external: true
    paper-db:
        external: true
    orange-db:
        external: true
    flow-db:
        external: true
    ping-db:
        external: true
