# This is an explanatory example, and it will not work out of the box.

# DO NOT USE SERVICES PORTS MAPPING!
# See down below the Traefik labels, it does the mapping.

# The same network as the Traefik
networks:
    default:
        name: marina
        external: true

# Zero downtime deployment works because of `healthcheck` and `deploy` settings.
services:
    app1:
        image: my-private-registry/app1:production
        env_file: .env.app1
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:<INTERNAL-PORT>" ]
            start_period: 120s
            interval: 5s
            timeout: 10s
            retries: 3
        deploy:
            update_config:
                order: start-first
                failure_action: rollback
            labels:
                - "traefik.http.routers.paper.rule=Host(`app1.com`)"
                - "traefik.http.services.paper.loadbalancer.server.port=<INTERNAL-PORT>"

    app2:
        image: my-private-registry/app2:production
        env_file: .env.app2
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:<INTERNAL-PORT>" ]
            start_period: 120s
            interval: 5s
            timeout: 10s
            retries: 3
        deploy:
            update_config:
                order: start-first
                failure_action: rollback
            labels:
                - "traefik.http.routers.paper.rule=Host(`app2.com`)"
                - "traefik.http.services.paper.loadbalancer.server.port=<INTERNAL-PORT>"

