# Reverse Proxy (traefik.io)
# Traefik: http://traefik.your-site.com
# Marina: http://marina.your-site.com

# Change the hosts below and hit DEPLOY!

# Joins to the `marina` network
networks:
    default:
        name: marina
        external: true

services:
    traefik:
        image: traefik:v3.3
        entrypoint: /bin/sh
        command:
            - -c
            - >
                mkdir -p /etc/traefik &&
                echo "$${CONFIG}" > /etc/traefik/dynamic.yml &&
                exec traefik
                --providers.file.filename=/etc/traefik/dynamic.yml
                --providers.swarm
                --api.insecure=true
                --entrypoints.web.address=:80
        environment:
            # Creates an entry for the `marina` service
            CONFIG: |
                http:
                  routers:
                    marina:
                      rule: "Host(`marina.your-site.com`)"
                      service: marina

                  services:
                    marina:
                      loadBalancer:
                        servers:
                          - url: "http://marina:8000"
        ports:
            - 80:80
            - 8080:8080
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
        deploy:
            labels:
                - "traefik.http.routers.traefik.rule=Host(`traefik.your-site.com`)"
                - "traefik.http.routers.traefik.entrypoints=web"
                - "traefik.http.routers.traefik.service=api@internal"
                - "traefik.http.services.traefik.loadbalancer.server.port=8080"
